- name: install node js
  yum:
   name: 
    - nodejs
    - make
    - gcc-c++
   state: present

- name: create roboshop user
  user:
    name: roboshop

- name: Download frontend archive 
  ansible.builtin.unarchive:
    src: "https://github.com/roboshop-devops-project/catalogue/archive/main.zip"
    dest: /tmp
    remote_src: yes #unarchive module will cpy the file from role to remote place so if we dont want to do that we have to give yes 

- name: Remove old content
  ansible.builtin.file:
    path: /home/roboshop/catalogue
    state: absent

- name: Copy extracted content to catalogue path
  ansible.builtin.copy:
    src: /tmp/catalogue-main/
    dest: /home/roboshop/catalogue  # now all the static content will be moved into html directory
    remote_src: yes
    owner: roboshop
    group: roboshop

- name: Install node js dependencies
  community.general.npm:
    path: /home/roboshop/catalogue
  become_user: roboshop # this task will become as user of roboshop and then will get executed

- name: setup systemd module
  copy:
    src: systemd.service
    dest: /etc/systemd/system/catalogue.service

- name: restart catalogue service
  systemd:
    name: catalogue
    state: restarted
    enabled: yes
    daemon_reload: yes
